/** Aligné sur v0_ui_import (globals.css) — primary rose ~ oklch(0.55 0.22 12) ≈ #E11D48 */
export const theme = {
  colors: {
    primary: "#E11D48",
    primaryForeground: "#FFFFFF",
    primaryMuted: "rgba(225, 29, 72, 0.12)",
    primaryLight: "#F43F5E",
    accent: "#E11D48",
    accentHover: "#BE123C",
    surface: "#FFFFFF",
    surfaceElevated: "#FFFFFF",
    background: "#FCFCFC",
    /** Bandeau login / zones sombres legacy */
    backgroundDark: "#1A1C2E",
    muted: "#F5F5F5",
    text: "#262626",
    textOnDark: "#FFFFFF",
    textSecondary: "#525252",
    textMuted: "#737373",
    border: "#E5E5E5",
    borderLight: "#E5E5E5",
    input: "#E5E5E5",
    ring: "#E11D48",
    success: "#16A34A",
    error: "#DC2626",
    warning: "#D97706",
    pastels: {
      pink: "#FFF1F2",
      blue: "#EFF6FF",
      green: "#F0FDF4",
      orange: "#FFF7ED",
      purple: "#FAF5FF",
    },
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  radius: {
    sm: 12,
    md: 16,
    lg: 24,
    xl: 28,
    pill: 9999,
    full: 9999,
  },
  typography: {
    h1: { fontSize: 32, fontWeight: "800", letterSpacing: -0.5 },
    h2: { fontSize: 24, fontWeight: "700", letterSpacing: -0.3 },
    h3: { fontSize: 18, fontWeight: "600" },
    body: { fontSize: 16, fontWeight: "400" },
    bodySmall: { fontSize: 14, fontWeight: "400" },
    caption: { fontSize: 12, fontWeight: "500" },
  },
  shadows: {
    sm: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 8,
      elevation: 3,
    },
    md: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.08,
      shadowRadius: 16,
      elevation: 6,
    },
    lg: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.12,
      shadowRadius: 24,
      elevation: 10,
    },
  },
};
