export const theme = {
  colors: {
    primary: "#1A1C2E",
    primaryLight: "#252840",
    accent: "#FF5F6D",
    accentHover: "#E84A5A",
    surface: "#FFFFFF",
    surfaceElevated: "#FFFFFF",
    background: "#F5F7FA",
    backgroundDark: "#1A1C2E",
    text: "#1A1C2E",
    textOnDark: "#FFFFFF",
    textSecondary: "#64748B",
    textMuted: "#94A3B8",
    border: "rgba(0,0,0,0.06)",
    borderLight: "#E2E8F0",
    success: "#10B981",
    error: "#EF4444",
    warning: "#F59E0B",
    pastels: {
      pink: "#FFE5E8",
      blue: "#E3F2FD",
      green: "#E8F5E9",
      orange: "#FFF3E0",
      purple: "#F3E8FF",
    },
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  radius: {
    sm: 12,
    md: 16,
    lg: 24,
    xl: 28,
    pill: 9999,
    full: 9999,
  },
  typography: {
    h1: { fontSize: 32, fontWeight: "800", letterSpacing: -0.5 },
    h2: { fontSize: 24, fontWeight: "700", letterSpacing: -0.3 },
    h3: { fontSize: 18, fontWeight: "600" },
    body: { fontSize: 16, fontWeight: "400" },
    bodySmall: { fontSize: 14, fontWeight: "400" },
    caption: { fontSize: 12, fontWeight: "500" },
  },
  shadows: {
    sm: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 8,
      elevation: 3,
    },
    md: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.08,
      shadowRadius: 16,
      elevation: 6,
    },
    lg: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.12,
      shadowRadius: 24,
      elevation: 10,
    },
  },
};
